[phases.setup]
nixPkgs = ["nodejs-18_x", "jdk17"]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build && cd ..",
  "./mvnw clean package -DskipTests"
]

[start]
cmd = "java -jar target/POCAS-0.0.1-SNAPSHOT.jar"
