[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["nodejs-18_x", "jdk17"]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build && cd ..",
  "./mvnw clean package -DskipTests",
  "mkdir -p src/main/resources/static",
  "cp -r frontend/build/* src/main/resources/static/"
]

[start]
cmd = "java -jar target/POCAS-0.0.1-SNAPSHOT.jar"
