[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["nodejs-18_x", "jdk17"]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build && cd ..",
  "./mvnw clean package -DskipTests",
  "mkdir -p target/classes",
  "cp -r frontend/build target/classes/static"
]

[start]
cmd = "java -jar target/POCAS-0.0.1-SNAPSHOT.jar"
